filetype plugin indent on
set tabstop=4
set shiftwidth=4
"set relativenumber
set number
set fileencoding=utf-8
syntax enable
filetype plugin on
set nocompatible

"Autocomlete in subfolders
set path+=**

"all mathing files when tab completing
set wildmenu

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
"Plug 'lervag/vimtex', { 'for': 'tex' }
Plug 'chriskempson/base16-vim'
Plug 'ying17zi/vim-live-latex-preview'
Plug 'altercation/vim-colors-solarized'
call plug#end()

 " Colors
if filereadable(expand("~/.vimrc_background"))
	let base16colorspace=256
 source ~/.vimrc_background
endif

"Set changing cursor
let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"

" optional reset cursor on start:
augroup myCmds
au!
autocmd VimEnter * silent !echo -ne "\e[2 q"
autocmd VimLeave * silent !echo -ne "\e[5 q"
augroup END

" Latex style
let g:tex_flavor='latex'
