config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  d_scripts:
    dst: ~/.scripts
    src: scripts
  d_termite:
    dst: ~/.config/termite
    src: config/termite
  f_ag.zsh-theme:
    dst: ~/.config/oh-my-zsh/custom/themes/ag.zsh-theme
    src: config/oh-my-zsh/custom/themes/ag.zsh-theme
  f_aliases:
    dst: ~/.config/aliases
    src: config/aliases
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_config.py:
    dst: ~/.config/qutebrowser/config.py
    src: config/qutebrowser/config.py
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_lock.sh:
    dst: ~/.config/lock/lock.sh
    src: config/lock/lock.sh
  f_pam_environment:
    dst: ~/.pam_environment
    src: pam_environment
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_zprofile:
    dst: ~/.zprofile
    src: zprofile
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_rifle.conf:
    src: config/ranger/rifle.conf
    dst: ~/.config/ranger/rifle.conf
  f_scope.sh:
    src: config/ranger/scope.sh
    dst: ~/.config/ranger/scope.sh
profiles:
  Jupiter:
    dotfiles:
    - f_xinitrc
  pluto:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_gitconfig
    - f_init.vim
    - d_polybar
    - d_i3
    - f_compton.conf
    - d_termite
    - d_scripts
    - f_config.py
    - f_aliases
    - f_zshrc
    - f_zprofile
    - f_pam_environment
    - f_lock.sh
    - f_ag.zsh-theme
    - f_rc.conf
    - f_rifle.conf
    - f_scope.sh
